image: node:10.9.0

pipelines:
  default:
    - step:
        deployment: production
        script:
          - npm ci
          - npm run build
          - npm run deploy -- --token "$FIREBASE_TOKEN"
