[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/en.html"
  status = 301

[[redirects]]
  from = "/en"
  to = "/en.html"
  status = 301

[[redirects]]
  from = "/de"
  to = "/de.html"
  status = 301
