[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/en.html"
  status = 301

[[redirects]]
  from = "/en"
  to = "/en.html"
  status = 301

[[redirects]]
  from = "/de"
  to = "/de.html"
  status = 301

[[redirects]]
  from = "/a11y"
  to = "https://docs.google.com/presentation/d/e/2PACX-1vTfSd7-aUuD737BDGXmw3xi4MS7HYTys9lKaR3pG0ZAlQfoU14odOgKjSY1Yx_r0agyX1JFgDW1vEwF/pub"
  status = 302

[[redirects]]
  from = "/oauth"
  to = "https://docs.google.com/presentation/d/e/2PACX-1vTPaIpWip0AHE4m_5DpxbOz3JmzoPxNFTXFJrpVNW65z8G6upGjH5DF02eePkfdmO_QViPD11fEJqhe/pub"
  status = 302
