module.exports = [
  {
    role: "Head of Development",
    company: "romeis Information Engineering",
    location: "Gelnhausen",
    from: "2023-03-01",
    description: {
      de: [
        "Technische Leitung eines Teams von 12 Software-Entwickler:innen. Planung, Architektur und Durchführung von Software-Projekten für Mittelstand und Konzerne.",
        "Strategische Positionierung und Weiterentwicklung des Unternehmens im Bereich der Digitalisierung und Industrie 4.0.",
        "Etablierung einer Standard-Architektur, vereinheitlichten Vorgehensweisen und begleitenden Software-Bibliotheken.",
      ],
      en: [
        "Technical leadership of a team of 12 software developers. Planning, architecture and execution of software projects for medium-sized companies and corporations.",
        "Strategic positioning and further development of the company in the field of digitalization and industry 4.0.",
        "Implementation of a standard architecture, unified procedures and accompanying software libraries.",
      ],
    },
    technologies: [
      "Kotlin",
      "Spring",
      "React",
      "TypeScript",
      "REST",
      "OAuth",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
    ],
  },
  {
    role: "Lead Developer",
    company: "rescueTABLET",
    location: "Hanau",
    from: "2019-11-01",
    description: {
      de: [
        "Mobile Einsatz-Unterstützung in Echtzeit für Feuerwehr und Rettungsdienste. Konzeption, Architektur und Implementierung von Features in enger Zusammenarbeit mit Stakeholdern und Kunden.",
        "Hoch-performante, offline-fähige Progressive Web App für Android, iOS und den Desktop.",
        "Schnittstellen-offene und hochverfügbare cloud-native Software-Architektur mit vollautomatisierter Continuous Delivery.",
      ],
      en: [
        "Real-time mobile mission support for fire brigades and emergency services. Concept, architecture and implementation of features in close collaboration with stakeholders and customers.",
        "High-performance, offline-capable progressive web app for Android, iOS and desktop.",
        "Open interface and highly available cloud-native software architecture with fully automated continuous delivery.",
      ],
    },
    technologies: [
      "Node.js",
      "React",
      "TypeScript",
      "REST",
      "Microservices",
      "AWS",
      "cloud-native",
      "Firebase",
    ],
  },
  {
    role: "Principal Software Engineer",
    company: "Qualifyze",
    location: "Frankfurt",
    from: "2021-07-01",
    until: "2023-02-28",
    description: {
      de: [
        "Leitung eines agilen Teams von fünf Entwickler:innen in einem schnell wachsenden Startup. Konzeption, Architektur und Implementierung von Features in enger Zusammenarbeit mit Stakeholdern und Kunden.",
        "Etablierung einer microservice-basierten cloud-native Software-Architektur und der vollautomatisierten Continuous Delivery.",
      ],
      en: [
        "Leading an agile team of five developers in a fast-growing start-up. Concept, architecture and implementation of features in close collaboration with stakeholders and customers.",
        "Establishment of a microservice-based cloud-native software architecture and fully automated continuous delivery.",
      ],
    },
    technologies: [
      "Node.js",
      "React",
      "TypeScript",
      "REST",
      "Microservices",
      "AWS",
      "serverless",
      "OAuth",
    ],
  },
  {
    role: "Lead Software Engineer",
    company: "Nortal AG",
    location: "Hanau",
    from: "2018-10-01",
    until: "2021-06-30",
    description: {
      de: [
        "Senior-Architekt und Lead Developer in einer Gruppe von crossfunktionalen Teams mit insgesamt ca. 60 Personen. Entwicklung einer Verwaltungssoftware für das Land Berlin.",
        "Ich habe die Niederlassung Rhein-Main gegründed und rekrutiere zur Zeit neue Mitarbeiterinnen und Mitarbeiter.",
      ],
      en: [
        "Senior architect and lead developer in a cross-functional group of teams with approx. 60 people involved in the development of an administrative software for the Berlin administration.",
        "I've founded the Rhein-Main office in Hanau and am currently recruiting a team of talented professionals.",
      ],
    },
    technologies: [
      "Kotlin",
      "Spring",
      "TypeScript",
      "React",
      "GraphQL",
      "Docker",
      "Kubernetes",
      "Microservices",
      "Node.js",
      "Electron",
    ],
  },
  {
    role: "Lead Software Engineer",
    company: "ChemSquare",
    location: "Frankfurt",
    from: "2018-06-01",
    until: "2018-08-31",
    description: {
      de: [
        "Lead-Developer in einem Start-Up für die Entwicklung eines Online-Marktplatzes für Chemikalien.",
      ],
      en: [
        "Lead developer in a start-up developing a B2B marketplace for the sourcing of chemical ingredients.",
      ],
    },
    technologies: [
      "Node.js",
      "GraphQL",
      "Gatsby",
      "React",
      "AWS",
      "serverless",
      "Algolia",
    ],
  },
  {
    role: "Senior Software Consultant",
    company: "PENTASYS",
    location: "Frankfurt",
    from: "2017-10-01",
    until: "2018-05-31",
    description: {
      de: [
        "Senior Front-End Developer für die Buchungsplattform des größten Reise-Dienstleisters Europas mit über 200k aktiven Benutzern. Mitentwicklung des internen Angular-Frameworks für über 100 Entwickler.",
      ],
      en: [
        "Senior Front-End Developer for the booking and fulfillment platform of the biggest travel technology provider in Europe with more than 200k active users. Development of the internal central Angular framework for more than 100 developers.",
      ],
    },
    technologies: ["Angular", "TypeScript", "Bootstrap"],
  },
  {
    role: "Senior Software Consultant",
    company: "bd4travel",
    location: "Frankfurt",
    from: "2014-12-01",
    until: "2017-10-31",
    description: {
      de: [
        "Intelligente Personalisierung für Reiseportale. Ein preisgekröntes Start-Up, das Reiseportale auf der ganzen Welt mit Analysen des Benutzerverhaltens, persönlichen Empfehlungen, Sortier-Algorithmen und Vorhersage-Werkzeugen versorgt.",
        "Mitglied eines agilen Entwicklungsteams mit geteilter Verantwortlichkeit für alle Aspekte der Produktentwicklung: Anforderungsanalyse, emergente Architektur, Datenbanken, Backend- und Frontend-Entwicklung, Machine Learning, Qualitätssicherung, DevOps, Skalierung und Wartung.",
      ],
      en: [
        "Intelligent personalization for travel. Award winning start-up providing travel websites around the world with user behavior analytics, personalized recommenders, sorting algorithms and prediction tools.",
        "Member of an agile development team with shared responsibilities for all aspects of product development: feature engineering, architecture, databases, backend and frontend development, machine learning, QA, devops, scaling and maintenance.",
      ],
    },
    technologies: [
      "Java",
      "JavaScript",
      "node.js",
      "ElasticSearch",
      "Hadoop",
      "HBase",
      "Spark",
      "RabbitMQ",
      "MongoDB",
      "AngularJS",
      "Swagger",
      "Docker",
    ],
  },
  {
    role: "Head of Development",
    company: "yocondo",
    location: "Düsseldorf",
    from: "2013-12-01",
    until: "2014-11-30",
    description: {
      de: [
        "Gründungsmitglied eines Start-Ups für die Entwicklung eines personalisierten Shopping-Assistenten.",
        "Architekt, Software-Engineer, SCRUM Master",
      ],
      en: [
        "Founding member of a start-up that created a personalized shopping assistant.",
        "Architect, software engineer, leader of a team of two developers and interns, Scrum master.",
      ],
    },
    technologies: [
      "Node.js",
      "CoffeeScript",
      "RabbitMQ",
      "ElasticSearch",
      "WebSockets",
      "MongoDB",
      "Angular",
      "Java",
      "Spring",
      "Vagrant",
      "Puppet",
      "AppFog",
      "Heroku",
      "AWS",
      "Azure",
    ],
  },
  {
    role: "Senior Consultant",
    company: "OPITZ Consulting",
    location: "Bad Homburg",
    from: "2011-06-01",
    until: "2013-11-30",
    description: {
      de: [
        "Consultant und Software-Engineer für die zentrale Unternehmenssoftware der TNT Innight GmbH (Logistik) mit Eclipse RCP und einem Spring-Backend.",
        "Entwicklung von Fachanwendungen für Kombiverkehr (Logistik).",
        "Mitglied des Competence Center Agile Development: Replikator für agile Prinzipien, Organisation von Agile Retreats und Coding Dojos.",
      ],
      en: [
        "Consultant and software engineer for the central operations software of TNT Innight GmbH based on Eclipse RCP with a Spring backend.",
        "Development of the operational software for Kombiverkehr (logistics).",
        "Member of the Competence Center Agile Development: replicator for agile principles, organization of agile retreats und coding dojos.",
      ],
    },
    technologies: [
      "Spring",
      "Oracle Database",
      "Eclipse RCP",
      "OSGi",
      "Activiti",
      "BPMN",
    ],
  },
  {
    role: "Senior Software Engineer",
    company: "Schütze Consulting",
    location: "Berlin",
    from: "2009-07-01",
    until: "2011-05-31",
    description: {
      de: [
        "Design, Architektur und Entwicklung einer Verwaltungs-Software für die Berliner Regierung mit JavaEE. Ca. 800 Anwender, Projektumfang ca. 8000 PT.",
        "Beratung für das Berliner IT-Service-Center.",
      ],
      en: [
        "Design, architecture and development of a administrative software for the Berlin administration based on JavaEE. Approx. 800 active users, scope approx. 8000 person days.",
        "Consulting for the IT service center of Berlin.",
      ],
    },
    technologies: [
      "JavaEE",
      "Oracle Database",
      "Oracle Application Server",
      "JBoss",
      "Spring",
    ],
  },
  {
    role: "Senior Software Engineer",
    company: "]init[ AG",
    location: "Berlin",
    from: "2007-10-01",
    until: "2009-06-30",
    description: {
      de: [
        "Konzept und Entwicklung einer SOA-Plattform für die G2C- und G2G-Kommunikation in Abu Dhabi. Single-Sign-on und Identity-Management.",
        "Anforderungsanalyse und technisches Projektmanagement für ein Soziales Netzwerk und eine Stellenbörse für das deutsche Auswärtige Amt.",
        "Technische Beratung bei der Entwicklung von XMeld, dem standardisierten XML-Austauschformat für deutsche Meldebehörden.",
      ],
      en: [
        "Concept and development of a SOA platform for G2C and G2G communications in Abu Dhabi. Single sign-on and identity management.",
        "Requirement analysis and technical project management for a social network and a classifieds portal for the German state department.",
        "Technical consulting for the development of XMeld, the standardized XML format for the communication between German registry offices.",
      ],
    },
    technologies: [
      "BEA WebLogic",
      "BEA AquaLogic",
      "BEA Portal",
      "Spring",
      "Beehive",
      "JBoss",
    ],
  },
  {
    role: "Senior Software Engineer",
    company: "Schütze Consulting",
    location: "Berlin",
    from: "2004-01-01",
    until: "2007-10-31",
    description: {
      de: [
        "Entwicklung JavaEE-basierter Web-Anwendungen für die Berliner Verwaltung.",
        "Verantwortlich für Release-Management, Continuous Integration und Qualitätssicherung.",
      ],
      en: [
        "Development of JavaEE-based web applications for the Berlin administration.",
        "Responsible for build and release management, continuous integration and QA.",
      ],
    },
    technologies: [
      "JavaEE",
      "Oracle Database",
      "Oracle Application Server",
      "JBoss",
      "Spring",
    ],
  },
];
